version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/url-shortener?authSource=admin
      - JWT_SECRET=my-secret-key-12345
      - APP_URL=http://localhost:3000
    depends_on:
      - mongodb

  frontend:
    build: ./Frontend1
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: